# Disable SELinux, Firewall, Packages
---
- hosts: all
  gather_facts: no
  become: true
  tasks:
  - name: selinux off
    shell: setenforce 0
  - name: selinux off
    shell: sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux
 
  - name: firewall off
    service:
      name: firewalld
      state: stopped
      enabled: false

  - name: Extra packages
    yum:
      name: 
        - bind-utils
        - man
        - man-pages
        - mlocate
        - sysstat
      state: present