---
- name: Create a VM from a template
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: 192.168.34.5
      username: student11 
      password: "password"
      validate_certs: False
      name: prdx-nsmaster12
      template: golden
      #datacenter: '192.168.34.5'
      folder: /ha-datacenter/vm/
      state: poweredon
      wait_for_ip_address: yes